name: Integration tests

on:
  workflow_call:

jobs:
    integration-tests:
        runs-on: ubuntu-22.04
        strategy:
          fail-fast: false
          matrix:
            juju: ["3.1/stable"]
            include:
              - libjuju: "3.1.2.0"
                juju: "3.1/stable"
                microk8s: "1.27-strict/stable"
        steps:
          - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
          - name: Install tox
            run: pip install tox
          - name: Setup operator environment
            uses: charmed-kubernetes/actions-operator@main
            with:
              juju-channel: ${{ matrix.juju }}
              provider: microk8s
              channel: ${{ matrix.microk8s }}
          - name: Run tests using tox
            run: tox -e integration
            env:
              LIBJUJU_VERSION: ${{ matrix.libjuju }}
          - name: Archive charmcraft logs
            if: failure()
            uses: actions/upload-artifact@v3
            with:
              name: charmcraft-logs
              path: /home/runner/.local/state/charmcraft/log/*.log
          - name: Archive juju crashdump
            if: failure()
            uses: actions/upload-artifact@v3
            with:
              name: juju-crashdump
              path: juju-crashdump-*.tar.xz